version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OUTPUT_DIR=/app/output_graphs
      - INTERNAL_DATA_DIR=/app/data_cache
    volumes:
      - output-data:/app/output_graphs
      - cache-data:/app/data_cache
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  output-data:
  cache-data:
